#!/usr/bin/env bash
# ==============================================================================
# vllm_serv: 환경 검증, uv 설정, 방화벽 등록 및 서빙 제어 스크립트 생성 원스톱 setup.sh
# ==============================================================================

set -eo pipefail

COLOR_GREEN='\033[0;32m'
COLOR_YELLOW='\033[1;33m'
COLOR_RED='\033[0;31m'
COLOR_CYAN='\033[0;36m'
COLOR_NC='\033[0m'

log_info() { echo -e "${COLOR_GREEN}[SETUP INFO]${COLOR_NC} $1"; }
log_warn() { echo -e "${COLOR_YELLOW}[SETUP WARN]${COLOR_NC} $1"; }
log_err()  { echo -e "${COLOR_RED}[SETUP ERROR]${COLOR_NC} $1"; }
log_step() { echo -e "\n${COLOR_CYAN}====================================================${COLOR_NC}\n${COLOR_CYAN}▶ $1${COLOR_NC}\n${COLOR_CYAN}====================================================${COLOR_NC}"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ -f "$SCRIPT_DIR/pyproject.toml" ]; then
    BASE_DIR="$SCRIPT_DIR"
elif [ -f "$SCRIPT_DIR/../pyproject.toml" ]; then
    BASE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
else
    BASE_DIR="$(pwd)"
fi
cd "$BASE_DIR"
mkdir -p "$BASE_DIR/logs"
touch "$BASE_DIR/logs/benchmark.log" "$BASE_DIR/logs/error.log" 2>/dev/null || true

if [ -f "$BASE_DIR/scripts/common.sh" ]; then
    source "$BASE_DIR/scripts/common.sh"
elif [ -f "$SCRIPT_DIR/common.sh" ]; then
    source "$SCRIPT_DIR/common.sh"
fi

WHEEL_PATH=""
SKIP_BUILD=0
SKIP_BENCHMARK=0
FORCE_BENCHMARK=0
FORCE_BUILD=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --wheel-path)
            WHEEL_PATH="$2"
            shift 2
            ;;
        --skip-build)
            SKIP_BUILD=1
            shift
            ;;
        --skip-benchmark)
            SKIP_BENCHMARK=1
            shift
            ;;
        --force-benchmark)
            FORCE_BENCHMARK=1
            shift
            ;;
        --force-build)
            FORCE_BUILD=1
            shift
            ;;
        --help|-h)
            echo "Usage: ./setup.sh [--wheel-path <PATH>] [--skip-build] [--skip-benchmark] [--force-benchmark] [--force-build]"
            exit 0
            ;;
        *)
            shift
            ;;
    esac
done

# ==============================================================================
# Step 0: Sudo Credential Acquisition & Keep-Alive Daemon
# (039-seed-pack-sudo-firewall-migration: FR-001, FR-002, FR-004)
# ==============================================================================
log_step "0. Sudo 관리자 권한 확보 및 유지"

SUDO_AVAILABLE=false
SUDO_KEEPALIVE_PID=""

if [ -t 0 ]; then
    # Interactive TTY environment: prompt for sudo password once
    log_info "대화형 TTY 환경 감지. sudo 비밀번호 1회 입력으로 관리자 권한을 확보합니다."
    if sudo -v 2>/dev/null; then
        SUDO_AVAILABLE=true
        log_info "✓ sudo 관리자 권한 승격 성공"

        # Background keepalive daemon: refresh sudo timestamp every 50 seconds
        (while true; do sudo -n true 2>/dev/null; sleep 50; done) &
        SUDO_KEEPALIVE_PID=$!
        trap 'kill $SUDO_KEEPALIVE_PID 2>/dev/null || true' EXIT INT TERM
        log_info "✓ sudo 타임스탬프 갱신 데몬 가동 (PID: $SUDO_KEEPALIVE_PID)"
    else
        log_warn "sudo 비밀번호 인증 실패 또는 취소. 방화벽 설정은 수동으로 진행해야 합니다."
    fi
else
    # Non-interactive (CI/CD, headless) environment
    log_info "비대화형 환경 감지. passwordless sudo 존재 여부를 확인합니다."
    if sudo -n true 2>/dev/null; then
        SUDO_AVAILABLE=true
        log_info "✓ passwordless sudo 사용 가능"
    else
        log_warn "비대화형 환경에서 sudo 권한을 확보할 수 없습니다."
        log_warn "방화벽 포트 개방은 복구 스크립트를 통해 수동으로 진행해야 합니다."

        # FR-004: Auto-generate configure_firewall.sh fallback script
        FIREWALL_SCRIPT="$BASE_DIR/scripts/configure_firewall.sh"
        if [ ! -f "$FIREWALL_SCRIPT" ]; then
            log_info "방화벽 복구 스크립트 자동 생성 중: $FIREWALL_SCRIPT"
            cat > "$FIREWALL_SCRIPT" << 'FIREWALL_EOF'
#!/usr/bin/env bash
# Auto-generated by vllm_serv setup.sh (039-seed-pack-sudo-firewall-migration & 054)
set -eo pipefail
if [ "$EUID" -ne 0 ]; then echo "ERROR: root 권한이 필요합니다. sudo $0"; exit 1; fi
PORTS=(8081 8082 8089 8090 8091)
if command -v ufw &>/dev/null && ufw status 2>/dev/null | grep -qi 'active'; then
    for p in "${PORTS[@]}"; do ufw allow "$p/tcp"; done
elif command -v firewall-cmd &>/dev/null && firewall-cmd --state 2>/dev/null | grep -qi 'running'; then
    for p in "${PORTS[@]}"; do firewall-cmd --permanent --add-port="$p/tcp"; done; firewall-cmd --reload
elif command -v nft &>/dev/null; then
    for p in "${PORTS[@]}"; do nft add rule inet filter input tcp dport "$p" accept 2>/dev/null || true; done
elif command -v iptables &>/dev/null; then
    for p in "${PORTS[@]}"; do iptables -C INPUT -p tcp --dport "$p" -j ACCEPT 2>/dev/null || iptables -A INPUT -p tcp --dport "$p" -j ACCEPT; done
fi
echo "방화벽 포트 구성 완료: ${PORTS[*]}"
FIREWALL_EOF
            chmod +x "$FIREWALL_SCRIPT"
            log_info "✓ 방화벽 복구 스크립트 생성 완료: $FIREWALL_SCRIPT"
        fi

        echo -e "\n${COLOR_YELLOW}========================================================================${COLOR_NC}"
        echo -e "${COLOR_YELLOW}⚠️ OS 방화벽 자동 개방 실패 (비대화형 / sudo 권한 부족)${COLOR_NC}"
        echo -e "${COLOR_YELLOW}------------------------------------------------------------------------${COLOR_NC}"
        echo -e "${COLOR_YELLOW}자동으로 복구 스크립트가 생성되었습니다: scripts/configure_firewall.sh${COLOR_NC}"
        echo -e "${COLOR_YELLOW}서버 서비스 포트(8081/tcp, 8089/tcp, 8090/tcp, 8091/tcp)를 개방하려면 관리자 권한으로 실행하세요:${COLOR_NC}"
        echo -e ""
        echo -e "    ${COLOR_GREEN}sudo ./scripts/configure_firewall.sh${COLOR_NC}"
        echo -e ""
        echo -e "${COLOR_YELLOW}========================================================================${COLOR_NC}\n"
    fi
fi

log_step "1. 필수 프로젝트 기본 파일 존재 여부 검증"

REQUIRED_FILES=(
    "pyproject.toml"
    "config/model_catalog.json"
    "config/server_config.json"
    "src/api/server.py"
    "src/core/process_manager.py"
    "src/core/model_downloader.py"
    "src/core/llama_manager.py"
    "src/core/auxiliary_manager.py"
    "scripts/benchmark_quality.py"
    "scripts/benchmark_context_window.py"
    "scripts/make_seed_pack.sh"
    "scripts/unpack_seed.sh"
)

MISSING_COUNT=0
for file in "${REQUIRED_FILES[@]}"; do
    if [ -f "$BASE_DIR/$file" ]; then
        log_info "✓ 필수 파일 존재: $file"
    else
        log_err "✗ 필수 파일 누락: $file"
        MISSING_COUNT=$((MISSING_COUNT + 1))
    fi
done

if [ "$MISSING_COUNT" -gt 0 ]; then
    log_err "누락된 필수 파일이 $MISSING_COUNT개 있습니다. 레포지토리 상태를 확인하세요."
    exit 1
fi

log_step "2. uv 패키지 매니저 및 파이썬 가상환경 구성"

if ! command -v uv &> /dev/null; then
    log_warn "uv 패키지 매니저가 설치되어 있지 않습니다. 자동 설치를 진행합니다..."
    curl -LsSf https://astral.sh/uv/install.sh | sh
    export PATH="$HOME/.cargo/bin:$PATH"
fi

if ! command -v uv &> /dev/null; then
    log_err "uv 설치에 실패했습니다. 수동으로 'curl -LsSf https://astral.sh/uv/install.sh | sh' 명령을 실행하세요."
    exit 1
fi

log_info "uv 버전: $(uv --version)"

# 혹시 이전 터미널에서 SIGSTOP(Ctrl+Z)으로 방치된 좀비 uv 파일 락 프로세스가 존재할 경우 자동 정리
pkill -f "uv pip install" 2>/dev/null || true

log_info "가상환경 고속 동기화 중 (uv sync --frozen)..."
if ! uv sync --frozen 2>/dev/null; then
    log_info "락파일(uv.lock) 불일치 감지 또는 가상환경 수립 필요: 일반 uv sync 동기화로 Fallback 진행 중..."
    uv sync
fi

# FR-007 / T010: lspci 기반 PCI 버스 물리 GPU 탐지 및 드라이버/CUDA 자동 가이드
log_info "PCI 버스 레벨 NVIDIA GPU 물리 장비 탐지 중 (lspci)..."
HAS_PCI_GPU=0
if command -v lspci &> /dev/null; then
    if lspci 2>/dev/null | grep -qi 'nvidia'; then
        HAS_PCI_GPU=1
        GPU_PCI_INFO=$(lspci 2>/dev/null | grep -i 'nvidia' | head -n 1)
        log_info "✓ PCI 버스에서 NVIDIA GPU 장비 감지 완료: $GPU_PCI_INFO"
    fi
fi

if [ "$HAS_PCI_GPU" -eq 1 ] && { ! command -v nvcc &> /dev/null || ! command -v nvidia-smi &> /dev/null; }; then
    log_warn "⚠️ 물리 NVIDIA GPU 장비가 존재하지만 nvcc 또는 nvidia-smi 드라이버가 감지되지 않았습니다."
    log_info "자동 드라이버 및 CUDA Toolkit 설치 헬퍼 실행 시도 중 (scripts/update_cuda_drivers.sh)..."
    if [ -f "$BASE_DIR/scripts/update_cuda_drivers.sh" ]; then
        bash "$BASE_DIR/scripts/update_cuda_drivers.sh" || log_warn "update_cuda_drivers.sh 실행 중 경고 발생"
    fi
fi

# FR-005 / T006: CUDA Toolkit (nvcc) 존재 여부 fail-fast 검증
log_info "NVIDIA CUDA Toolkit (nvcc) 빌드 환경 검증 중..."
if ! command -v nvcc &> /dev/null; then
    log_err "NVIDIA CUDA Toolkit (nvcc)가 감지되지 않았습니다."
    log_err "llama-cpp-python CUDA 가속 빌드를 위해 nvcc 설치가 필수입니다."
    log_err "설치: sudo apt install nvidia-cuda-toolkit 또는 https://developer.nvidia.com/cuda-downloads"
    log_err "CPU 전용 폴백은 허용되지 않습니다. setup.sh를 즉시 중단합니다."
    exit 1
fi
log_info "✓ nvcc 감지 완료: $(nvcc --version | grep release | head -n 1)"

# FR-005 / T006: nvidia-smi GPU 드라이버 fail-fast 검증
log_info "NVIDIA GPU 가속 드라이버 및 nvidia-smi 검증 중..."
if ! command -v nvidia-smi &> /dev/null; then
    log_err "nvidia-smi 명령어를 찾을 수 없습니다."
    log_err "NVIDIA GPU 가속 서빙을 위해 GPU 드라이버 설치가 필수입니다."
    log_err "CPU 전용 폴백은 허용되지 않습니다. setup.sh를 즉시 중단합니다."
    exit 1
fi

GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader | head -n 1)
VRAM_TOTAL=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader | head -n 1)
log_info "✓ NVIDIA GPU 감지 완료: $GPU_NAME (총 VRAM: $VRAM_TOTAL)"

# FR-001 / FR-002 / FR-003: CPU & GPU 하드웨어 명령어 세트 감지 및 CMAKE_ARGS 동적 생성
VENV_PYTHON="$BASE_DIR/.venv/bin/python"
if [ ! -f "$VENV_PYTHON" ]; then
    VENV_PYTHON="python3"
fi

log_info "CPU 명령어 세트, GPU Compute Capability 및 플랫폼 프로필 감지 수행 중..."
"$VENV_PYTHON" -m src.core.cpu_detector --report || true

MATCHED_PROFILE=$("$VENV_PYTHON" -m src.core.cpu_detector --match-profile 2>/dev/null || echo "unknown-hardware-profile")
log_info "✓ 감지 및 매칭된 타겟 플랫폼 프로필: $MATCHED_PROFILE"

DETECTED_CMAKE_ARGS=$("$VENV_PYTHON" -m src.core.cpu_detector --format cmake 2>/dev/null || echo "-DGGML_CUDA=ON -DGGML_AVX=OFF -DGGML_AVX2=OFF -DGGML_F16C=OFF -DGGML_FMA=OFF")
log_info "적용할 동적 CMAKE_ARGS: $DETECTED_CMAKE_ARGS"

# FR-001..FR-005 (055-fix-migration-setup-fallback): 4단계 결정론적 우선순위 휠 복원 & 3중 정합성 검증 파이프라인
INSTALLED_VIA_FAST_TRACK=0

# Tier 1: CLI 명시 전달 커스텀 휠 경로 (--wheel-path)
if [ -n "$WHEEL_PATH" ] && [ -f "$WHEEL_PATH" ]; then
    log_info "⚡ CLI 명시 커스텀 휠 경로($WHEEL_PATH) Fast-Track 복원을 시작합니다..."
    if uv pip install "$WHEEL_PATH" --force-reinstall --no-index; then
        log_info "CUDA GPU 가속 지원 검증 중 (llama_supports_gpu_offload())..."
        GPU_CHECK_STATUS=0
        GPU_CHECK_OUTPUT=$("$VENV_PYTHON" -c "
import sys, llama_cpp
fn = getattr(llama_cpp, 'llama_supports_gpu_offload', None) or getattr(llama_cpp, 'llama_supports_gpu', None)
if fn is None:
    print('ERROR: No GPU check function found in llama_cpp', file=sys.stderr)
    sys.exit(1)
if not fn():
    print('ERROR: llama_supports_gpu_offload() returned False', file=sys.stderr)
    sys.exit(2)
" 2>&1) || GPU_CHECK_STATUS=$?

        if [ "$GPU_CHECK_STATUS" -eq 0 ]; then
            log_info "✓ CLI 커스텀 휠 Fast-Track 설치 및 CUDA GPU 가속 활성화 확인 완료."
            INSTALLED_VIA_FAST_TRACK=1
        else
            log_warn "⚠️ [FAST-TRACK FAIL] CLI 커스텀 휠 GPU 가속 검증 실패: $GPU_CHECK_OUTPUT"
        fi
    fi
fi

# Tier 2: 현지 파이썬 가상환경 (.venv) 기존 휠 3중 정합성 검증 (0.05s 고속 리턴)
if [ "$INSTALLED_VIA_FAST_TRACK" -eq 0 ] && [ "$FORCE_BUILD" -eq 0 ] && [ -z "$WHEEL_PATH" ]; then
    log_info "기존 파이썬 가상환경(.venv) 내 llama-cpp-python CUDA 가속 지원 여부 사전 검증 중..."
    PRECHECK_GPU=$("$VENV_PYTHON" -c "
import llama_cpp
fn = getattr(llama_cpp, 'llama_supports_gpu_offload', None) or getattr(llama_cpp, 'llama_supports_gpu', None)
print('True' if fn and fn() else 'False')
" 2>/dev/null || echo "False")

    if [ "$PRECHECK_GPU" = "True" ]; then
        log_info "✓ 기존 가상환경 내 llama-cpp-python CUDA GPU 가속 활성화 확인 완료 (0.05s 소스 컴파일 스킵됨)."
        INSTALLED_VIA_FAST_TRACK=1
    fi
fi

# Tier 3: Seed Pack 수록 사전 빌드 휠 Fast-Track (wheels/${MATCHED_PROFILE}/*.whl)
if [ "$INSTALLED_VIA_FAST_TRACK" -eq 0 ] && [ "$FORCE_BUILD" -eq 0 ]; then
    LEGACY_WHEEL=""
    PROFILE_WHEEL_DIR="wheels/${MATCHED_PROFILE}"
    if [ -d "$PROFILE_WHEEL_DIR" ]; then
        LEGACY_WHEEL=$(ls -v "$PROFILE_WHEEL_DIR"/llama_cpp_python*.whl 2>/dev/null | tail -n 1 || true)
    fi
    if [ -z "$LEGACY_WHEEL" ]; then
        LEGACY_WHEEL=$(ls -v wheels/*/llama_cpp_python*.whl 2>/dev/null | tail -n 1 || true)
    fi
    if [ -z "$LEGACY_WHEEL" ]; then
        LEGACY_WHEEL=$(ls -v wheels/llama_cpp_python*.whl 2>/dev/null | tail -n 1 || true)
    fi

    if [ -n "$LEGACY_WHEEL" ] && [ -f "$LEGACY_WHEEL" ]; then
        log_info "⚡ 사전 빌드 휠($LEGACY_WHEEL) Fast-Track 복원을 시작합니다..."
        log_info "C++ 소스 재컴파일을 건너뛰고 사전 빌드 휠을 가상환경(.venv)에 고속 설치합니다..."
        WHEEL_FIND_DIR="$(dirname "$LEGACY_WHEEL")"
        if uv pip install "$LEGACY_WHEEL" --force-reinstall --no-index --find-links "$WHEEL_FIND_DIR"; then
            log_info "CUDA GPU 가속 지원 검증 중 (llama_supports_gpu_offload())..."
            GPU_CHECK_STATUS=0
            GPU_CHECK_OUTPUT=$("$VENV_PYTHON" -c "
import sys, llama_cpp
fn = getattr(llama_cpp, 'llama_supports_gpu_offload', None) or getattr(llama_cpp, 'llama_supports_gpu', None)
if fn is None:
    print('ERROR: No GPU check function found in llama_cpp', file=sys.stderr)
    sys.exit(1)
if not fn():
    print('ERROR: llama_supports_gpu_offload() returned False', file=sys.stderr)
    sys.exit(2)
" 2>&1) || GPU_CHECK_STATUS=$?

            if [ "$GPU_CHECK_STATUS" -eq 0 ]; then
                log_info "✓ 사전 빌드 휠 Fast-Track 설치 및 CUDA GPU 가속 활성화 확인 완료 (C++ 소스 재컴파일 스킵됨)"
                INSTALLED_VIA_FAST_TRACK=1
            else
                CAUSE="GPU_CHECK_FAILED (알 수 없는 검증 오류)"
                if [[ "$GPU_CHECK_OUTPUT" == *"Illegal instruction"* ]] || [[ "$GPU_CHECK_STATUS" -eq 132 ]]; then
                    CAUSE="SIGILL_ILLEGAL_INSTRUCTION (호스트 CPU에서 지원하지 않는 AVX 명령어 유입 감지)"
                elif [[ "$GPU_CHECK_OUTPUT" == *"returned False"* ]]; then
                    CAUSE="GPU_OFFLOAD_FALSE (llama_supports_gpu_offload() 반환값 False)"
                elif [[ "$GPU_CHECK_OUTPUT" == *"ImportError"* ]] || [[ "$GPU_CHECK_OUTPUT" == *"cannot open shared object"* ]]; then
                    CAUSE="SHARED_LIB_IMPORT_ERROR (공유 라이브러리/CUDA 드라이버 미로드)"
                fi

                log_warn "⚠️ [FAST-TRACK FAIL] 사전 빌드 휠 복원 후 GPU 가속 검증 실패: $CAUSE"
                log_warn "--- [FAST-TRACK FAIL TRACEBACK] ---"
                echo "$GPU_CHECK_OUTPUT" | while read -r line; do log_warn "  $line"; done
                log_warn "------------------------------------"
                log_warn "C++ 소스 컴파일 파이프라인으로 Fallback합니다."
            fi
        else
            log_warn "⚠️ 사전 빌드 휠 설치 실패. C++ 소스 컴파일 파이프라인으로 Fallback합니다."
        fi
    fi
fi

# Tier 4: 동적 C++ 소스 재컴파일 Fallback 및 조건부 uv 캐시 검증 파이프라인
if [ "$INSTALLED_VIA_FAST_TRACK" -eq 0 ]; then
    if [ "$SKIP_BUILD" -eq 1 ]; then
        log_err "--skip-build 플래그가 설정되었으나 사전 휠 복원에 실패하여 setup.sh를 중단합니다."
        exit 1
    fi

    if [ "$FORCE_BUILD" -eq 1 ]; then
        log_info "🔥 --force-build 플래그 감지: uv 휠 캐시 무효화(--no-cache-dir) 및 C++ 소스 강제 재컴파일을 수행합니다..."
        log_info "기존 패키지 정리 중 (uv pip uninstall llama-cpp-python)..."
        uv pip uninstall -y llama-cpp-python 2>/dev/null || true

        trap 'log_err "❌ C++ 컴파일 중단 감지. 결함 가상환경을 원자적으로 cleanup(uninstall)합니다."; uv pip uninstall -y llama-cpp-python 2>/dev/null || true' ERR INT TERM

        log_info "CUDA 및 CPU 최적화 적용 llama-cpp-python C++ 소스 강제 재컴파일 구동 중 (--no-cache-dir)..."
        CMAKE_ARGS="$DETECTED_CMAKE_ARGS" uv pip install --no-cache-dir --force-reinstall "llama-cpp-python[server]" --no-binary llama-cpp-python
        BUILD_STATUS=$?

        trap - ERR INT TERM

        if [ "$BUILD_STATUS" -ne 0 ]; then
            log_err "llama-cpp-python CUDA 재컴파일에 실패했습니다."
            uv pip uninstall -y llama-cpp-python 2>/dev/null || true
            exit 1
        fi
        log_info "✓ llama-cpp-python C++ 소스 동적 강제 재컴파일 및 설치 완료"
    else
        log_info "1단계: uv 휠 캐시 정상 여부 실측 검증 중..."
        CMAKE_ARGS="$DETECTED_CMAKE_ARGS" uv pip install "llama-cpp-python[server]" --no-binary llama-cpp-python 2>/dev/null || true

        if "$VENV_PYTHON" "$BASE_DIR/scripts/verify_wheel_binary.py" --check-live 2>/dev/null; then
            log_info "✓ [UV CACHE REUSED] 캐시 휠의 CUDA 가속 검증을 통과했습니다. 고속 재사용을 진행합니다."
        else
            log_warn "⚠️ [UV CACHE INVALID] uv 캐시 휠이 CPU 전용으로 감지되었습니다. 캐시 무효화(--no-cache-dir) 및 C++ 소스 재컴파일을 수행합니다..."
            log_info "기존 결함 패키지 정리 중 (uv pip uninstall llama-cpp-python)..."
            uv pip uninstall llama-cpp-python 2>/dev/null || true

            trap 'log_err "❌ C++ 컴파일 중단 감지. 결함 가상환경을 원자적으로 cleanup(uninstall)합니다."; uv pip uninstall -y llama-cpp-python 2>/dev/null || true' ERR INT TERM

            log_info "CUDA 및 CPU 최적화 적용 llama-cpp-python C++ 소스 재컴파일 구동 중 (--no-cache-dir)..."
            log_info "이 과정은 C++ 소스 재컴파일이므로 수 분이 소요될 수 있습니다..."
            CMAKE_ARGS="$DETECTED_CMAKE_ARGS" uv pip install --no-cache-dir "llama-cpp-python[server]" --no-binary llama-cpp-python
            BUILD_STATUS=$?

            trap - ERR INT TERM

            if [ "$BUILD_STATUS" -ne 0 ]; then
                log_err "llama-cpp-python CUDA 재컴파일에 실패했습니다."
                uv pip uninstall -y llama-cpp-python 2>/dev/null || true
                exit 1
            fi
            log_info "✓ llama-cpp-python C++ 소스 동적 재컴파일 및 설치 완료"
        fi
    fi

    log_info "CUDA GPU 가속 지원 최종 검증 중 (llama_supports_gpu_offload())..."
    if ! "$VENV_PYTHON" "$BASE_DIR/scripts/verify_wheel_binary.py" --check-live; then
        log_err "GPU 가속 지원 검증 실패: CUDA GPU 가속이 활성화되지 않았습다."
        log_err "CPU 전용 폴백은 허용되지 않습니다. setup.sh를 즉시 중단합니다."
        uv pip uninstall -y llama-cpp-python 2>/dev/null || true
        exit 1
    fi
    log_info "✓ CUDA GPU 가속 활성화 최종 확인 완료"
fi

# ==============================================================================
# Step 2.5: SQLite DB Auto-Initialization (T011)
# ==============================================================================
log_step "2.5. SQLite 메트릭 DB 자동 초기화"
if [ -f "$BASE_DIR/scripts/seed_db.py" ]; then
    log_info "메트릭/대시보드 DB 스키마 및 시드 데이터 검증/초기화 중 (scripts/seed_db.py)..."
    "$VENV_PYTHON" "$BASE_DIR/scripts/seed_db.py" || log_warn "seed_db.py 실행 중 경고 발생"
fi

# ==============================================================================
# Step 2.6: Essential GGUF Model Auto-Provisioning (092-setup-auto-model-download: FR-001..FR-008, T007)
# ==============================================================================
log_step "2.6. 필수 GGUF 모델 가중치 유무 점검 및 자동 프로비저닝"
if [ -f "$BASE_DIR/scripts/ensure_models.py" ]; then
    log_info "3종 필수 모델(qwen3.5-4b, bge-m3, bge-reranker-v2-m3) 점검 및 자동 다운로드 가동 중..."
    "$VENV_PYTHON" "$BASE_DIR/scripts/ensure_models.py" || {
        log_err "필수 GGUF 모델 다운로드/검증 실패!"
        log_err "수동 다운로드 가이드: uv run python scripts/benchmark_quality.py --auto-download --real"
        exit 1
    }
fi

log_info "🧹 [FR-006] 사전 가동 중인 서빙 프로세스 및 포트 점유 정리 (Pre-execution cleanup)..."
if [ -f "$BASE_DIR/scripts/stop_server.sh" ]; then
    "$BASE_DIR/scripts/stop_server.sh" 2>/dev/null || true
elif [ -f "$BASE_DIR/stop_server.sh" ]; then
    "$BASE_DIR/stop_server.sh" 2>/dev/null || true
fi

# ==============================================================================
# Step 2.7: Asset Audit & Cleanup (T011)
# ==============================================================================
log_step "2.7. 프로젝트 자산 정밀 스캔 및 레거시 격리 정돈"
if [ -f "$BASE_DIR/scripts/audit_assets.py" ]; then
    log_info "프로젝트 디렉토리 자산 감사 수행 중 (scripts/audit_assets.py)..."
    "$VENV_PYTHON" "$BASE_DIR/scripts/audit_assets.py" || log_warn "audit_assets.py 검사 완료"
fi

# ==============================================================================
# Step 2.8: 4단계 모듈화 벤치마크 파이프라인 (095-setup-benchmark-model-selection: FR-001..FR-008)
# Stage 1: 모델 다운로드 (Step 2.6 ensure_models.py 연동 완수)
# Stage 2: 헤더 무결성 실체적 검증 (verify_model_integrity)
# Stage 3: 임시 서빙 가동 및 컨텍스트 윈도우(2K~16K) 실측 GPU VRAM/TPS 벤치마크
# Stage 4: 최적 서비스 모델 선정 및 컨텍스트 윈도우 크기 결정 -> config/server_config.json 원자적 반영
# ==============================================================================
log_step "2.8. 4단계 모듈화 벤치마크 & 최적 서비스 모델/컨텍스트 선정"
if [ "$SKIP_BENCHMARK" -eq 1 ]; then
    log_info "⏩ --skip-benchmark 옵션 감지: 3단계 실측 벤치마크 스킵 모드로 모듈 구동 중..."
    if [ -f "$BASE_DIR/scripts/benchmark_context_window.py" ]; then
        "$VENV_PYTHON" "$BASE_DIR/scripts/benchmark_context_window.py" --skip-benchmark || log_warn "benchmark_context_window.py --skip-benchmark 실행 중 경고 발생"
    fi
elif [ "$FORCE_BENCHMARK" -eq 1 ]; then
    log_info "🔥 --force-benchmark 옵션 감지: 카탈로그 전체 LLM 후보 모델 대상 강제 실측 벤치마킹 수행 중..."
    if [ -f "$BASE_DIR/scripts/benchmark_context_window.py" ]; then
        "$VENV_PYTHON" "$BASE_DIR/scripts/benchmark_context_window.py" --force-benchmark || log_warn "benchmark_context_window.py 실행 중 경고 발생"
    fi
else
    if [ -f "$BASE_DIR/scripts/benchmark_context_window.py" ]; then
        log_info "4단계 모듈화 벤치마크 및 설정 자동 반영 수행 중 (scripts/benchmark_context_window.py)..."
        "$VENV_PYTHON" "$BASE_DIR/scripts/benchmark_context_window.py" || log_warn "benchmark_context_window.py 실행 중 경고 발생"
    fi
fi


log_step "3. 서버 포트 조회 및 네트워크 방화벽 등록"

SERVER_PORT=$(get_configured_port main)
DASHBOARD_PORT=$(get_configured_port dashboard)
EMBEDDING_PORT=$(get_configured_port embedding)
RERANK_PORT=$(get_configured_port rerank)

log_info "서빙 포트 설정: $SERVER_PORT/tcp (대시보드: $DASHBOARD_PORT, 임베딩: $EMBEDDING_PORT, 리랭커: $RERANK_PORT)"

FIREWALL_PORTS=("$SERVER_PORT" "$DASHBOARD_PORT" 8089 "$EMBEDDING_PORT" "$RERANK_PORT")

configure_os_firewall() {
    if command -v ufw &> /dev/null; then
        log_info "ufw 방화벽 감지. 서비스 포트 개방 중..."
        if [ "$SUDO_AVAILABLE" = true ]; then
            for port in "${FIREWALL_PORTS[@]}"; do
                sudo ufw allow "${port}/tcp" 2>/dev/null
                log_info "✓ sudo ufw allow ${port}/tcp"
            done
            sudo ufw status verbose 2>/dev/null
        else
            log_warn "sudo 권한 미확인: ufw 서비스 포트 개방 복구 가이드 생성 완료 (scripts/configure_firewall.sh)"
        fi
    elif command -v firewall-cmd &> /dev/null; then
        log_info "firewalld 방화벽 감지. 서비스 포트 영구 등록 중..."
        if [ "$SUDO_AVAILABLE" = true ]; then
            for port in "${FIREWALL_PORTS[@]}"; do
                sudo firewall-cmd --permanent --add-port="${port}/tcp" 2>/dev/null
                log_info "✓ firewall-cmd --permanent --add-port=${port}/tcp"
            done
            sudo firewall-cmd --reload 2>/dev/null
            log_info "firewalld 리로드 완료."
        else
            log_warn "sudo 권한 미확인: firewalld 서비스 포트 개방 복구 가이드 생성 완료 (scripts/configure_firewall.sh)"
        fi
    elif command -v nft &> /dev/null; then
        log_info "nftables 방화벽 감지. 서비스 포트 허용 규칙 등록 중..."
        if [ "$SUDO_AVAILABLE" = true ]; then
            for port in "${FIREWALL_PORTS[@]}"; do
                sudo nft add rule inet filter input tcp dport "${port}" accept 2>/dev/null || \
                    sudo nft add rule ip filter INPUT tcp dport "${port}" accept 2>/dev/null || true
            done
        fi
    elif command -v iptables &> /dev/null; then
        log_info "iptables 방화벽 감지. 서비스 포트 허용 규칙 등록 중..."
        if [ "$SUDO_AVAILABLE" = true ]; then
            for port in "${FIREWALL_PORTS[@]}"; do
                sudo iptables -C INPUT -p tcp --dport "${port}" -j ACCEPT 2>/dev/null || \
                    sudo iptables -A INPUT -p tcp --dport "${port}" -j ACCEPT 2>/dev/null
                log_info "✓ iptables 포트 ${port}/tcp 규칙 등록 완료"
            done
        fi
    else
        log_info "활성화된 OS 방화벽 패키지를 감지하지 못했습니다. (포트: ${FIREWALL_PORTS[*]})"
    fi
}

try_optional_step "OS 방화벽 설정" configure_os_firewall



log_step "4. 서버 구동/종료/상태 제어 쉘 스크립트 생성"

mkdir -p "$BASE_DIR/scripts"
mkdir -p "$BASE_DIR/logs"

# 4.1 start_server.sh 생성
cat << 'EOF' > "$BASE_DIR/scripts/start_server.sh"
#!/usr/bin/env bash
# ==============================================================================
# vllm_serv: 백그라운드 데몬 서버 구동 스크립트 (start_server.sh)
# llama.cpp C++ 바이너리 자동 빌드 및 모델 자동 다운로드 파이프라인 수행
# Port 8081 메인 API 서버 및 Port 8082 웹 대시보드 동시 Readiness & 원자적 롤백 지원
# ==============================================================================

set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "$SCRIPT_DIR/pyproject.toml" ]; then
    BASE_DIR="$SCRIPT_DIR"
elif [ -f "$SCRIPT_DIR/../pyproject.toml" ]; then
    BASE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
else
    BASE_DIR="$(pwd)"
fi
cd "$BASE_DIR"

PID_FILE="$BASE_DIR/vllm_serv.pid"
DASHBOARD_PID_FILE="$BASE_DIR/vllm_dashboard.pid"
LOG_FILE="$BASE_DIR/logs/server.log"
DASHBOARD_LOG_FILE="$BASE_DIR/logs/dashboard.log"

COLOR_GREEN='\033[0;32m'
COLOR_YELLOW='\033[1;33m'
COLOR_RED='\033[0;31m'
COLOR_CYAN='\033[0;36m'
COLOR_NC='\033[0m'

SERVER_RUNNING=$(pgrep -f "src.api.server" || true)
DASH_RUNNING=$(pgrep -f "uvicorn src.api.main:app" || true)
if [ -n "$SERVER_RUNNING" ] || [ -n "$DASH_RUNNING" ]; then
    echo -e "${COLOR_YELLOW}[SERVER WARN] 이미 구동 중이거나 단독 상주 중인 서버/대시보드 프로세스가 감지되었습니다.${COLOR_NC}"
    [ -n "$SERVER_RUNNING" ] && echo -e "  - 8081 메인 서버 PID: $SERVER_RUNNING"
    [ -n "$DASH_RUNNING" ] && echo -e "  - 8082 대시보드 PID: $DASH_RUNNING"
    echo -e "${COLOR_YELLOW}기존 프로세스를 먼저 종료하려면 './stop_server.sh' 명령을 실행한 후 다시 시도하세요.${COLOR_NC}"
    exit 1
fi


echo -e "${COLOR_CYAN}[SERVER] vllm_serv 인퍼런스 서빙 서버 및 웹 대시보드 구동 파이프라인을 시작합니다...${COLOR_NC}"
echo -e "${COLOR_CYAN}[SERVER] 하드웨어 가속 사전 점검(Pre-flight check) 수행 중...${COLOR_NC}"
if ! uv run python -m src.core.cpu_detector --check-preflight; then
    echo -e "${COLOR_RED}[SERVER ERROR] 사전 하드웨어 점검 실패! 백그라운드 서버 데몬을 구동하지 않고 즉시 종료합니다.${COLOR_NC}"
    echo -e "${COLOR_YELLOW}해결 가이드: NVIDIA GPU 드라이버(nvidia-smi) 및 CUDA Compiler(nvcc) 환경을 확인하세요.${COLOR_NC}"
    exit 1
fi
echo -e "${COLOR_GREEN}[SERVER] ✓ 하드웨어 가속 사전 점검 완료 (GPU CUDA 가속 활성)${COLOR_NC}"

echo -e "${COLOR_GREEN}[SERVER] 1. llama-server 바이너리 빌드 상태 및 모델 가중치 자동 다운로드 파이프라인 가동${COLOR_NC}"
echo -e "${COLOR_GREEN}[SERVER] 2. 기본 VRAM 상주 서빙 모델(qwen3.5-4b) VRAM 100% 오프로드 검증 수행${COLOR_NC}"
echo -e "${COLOR_GREEN}[SERVER] 3. 8081 메인 로그: $LOG_FILE | 8082 대시보드 로그: $DASHBOARD_LOG_FILE${COLOR_NC}"

mkdir -p "$BASE_DIR/logs"

# 8081 메인 API 서버 및 8082 웹 대시보드 데몬 동시 백그라운드 가동 (uv run 기반)
nohup setsid uv run python -m src.api.server < /dev/null > "$LOG_FILE" 2>&1 &
SERVER_PID=$!
nohup setsid uv run python -m uvicorn src.api.main:app --host 0.0.0.0 --port 8082 < /dev/null > "$DASHBOARD_LOG_FILE" 2>&1 &
DASHBOARD_PID=$!

sleep 0.5
ACTUAL_SERVER_PID=$(pgrep -f "src.api.server" | tail -n 1 || echo "$SERVER_PID")
ACTUAL_DASHBOARD_PID=$(pgrep -f "uvicorn src.api.main:app" | tail -n 1 || echo "$DASHBOARD_PID")

echo "$ACTUAL_SERVER_PID" > "$PID_FILE"
echo "$ACTUAL_DASHBOARD_PID" > "$DASHBOARD_PID_FILE"

echo -e "${COLOR_GREEN}✓ 서버 데몬 백그라운드 구동 시작! (8081 PID: $ACTUAL_SERVER_PID, 8082 PID: $ACTUAL_DASHBOARD_PID)${COLOR_NC}"

SERVER_HOST=$(uv run python -c "from src.core.config_manager import ConfigManager; print(ConfigManager().get_server_config().get('host', '127.0.0.1'))" 2>/dev/null || echo "127.0.0.1")
SERVER_PORT=$(uv run python -c "from src.core.config_manager import ConfigManager; print(ConfigManager().get_server_config().get('port', 8081))" 2>/dev/null || echo "8081")

CURL_HOST="$SERVER_HOST"
if [ "$CURL_HOST" = "0.0.0.0" ]; then
    CURL_HOST="127.0.0.1"
fi

# 동시 Readiness 검증 대기 (최대 30초)
echo -n "[SERVER] 8081 메인 서버 및 8082 대시보드 동시 READY 상태 대기 중 (최대 30초)..."
READY=0
for i in {1..30}; do
    P8081_OK=0
    P8082_OK=0
    if curl -s "http://$CURL_HOST:$SERVER_PORT/health" > /dev/null 2>&1 || curl -s "http://$CURL_HOST:$SERVER_PORT/v1/models" > /dev/null 2>&1; then
        P8081_OK=1
    fi
    if curl -s "http://$CURL_HOST:8082/" > /dev/null 2>&1; then
        P8082_OK=1
    fi

    if [ "$P8081_OK" -eq 1 ] && [ "$P8082_OK" -eq 1 ]; then
        READY=1
        break
    fi
    echo -n "."
    sleep 1
done

if [ "$READY" -eq 1 ]; then
    echo -e "\n${COLOR_GREEN}✓ 8081 메인 인퍼런스 서버 및 8082 웹 대시보드 동시 가동 완료!${COLOR_NC}"
    echo -e "OpenAI API 엔드포인트: http://$SERVER_HOST:$SERVER_PORT/v1/chat/completions"
    echo -e "웹 대시보드 URL: http://$SERVER_HOST:8082/"
    exit 0
else
    echo -e "\n${COLOR_RED}[SERVER ERROR] [SERVER DIAGNOSTICS] 30초 이내 8081/8082 동시 Readiness 검증 실패! 원자적 롤백(Clean Exit)을 수행합니다.${COLOR_NC}"
    echo -e "${COLOR_RED}최근 서버 로그 출력 (tail -n 15):${COLOR_NC}"
    tail -n 15 "$LOG_FILE" 2>/dev/null || true
    [ -n "$ACTUAL_SERVER_PID" ] && kill -9 "$ACTUAL_SERVER_PID" 2>/dev/null || true
    [ -n "$ACTUAL_DASHBOARD_PID" ] && kill -9 "$ACTUAL_DASHBOARD_PID" 2>/dev/null || true
    pkill -f "src.api.server" 2>/dev/null || true
    pkill -f "uvicorn src.api.main:app" 2>/dev/null || true
    rm -f "$PID_FILE" "$DASHBOARD_PID_FILE"
    exit 1
fi
EOF

chmod +x "$BASE_DIR/scripts/start_server.sh"
ln -sf "$BASE_DIR/scripts/start_server.sh" "$BASE_DIR/start_server.sh"
log_info "✓ 생성 완료: scripts/start_server.sh (루트 심볼릭 링크 ./start_server.sh)"

# 4.2 stop_server.sh 생성
cat << 'EOF' > "$BASE_DIR/scripts/stop_server.sh"
#!/usr/bin/env bash
# ==============================================================================
# vllm_serv: 서빙 서버 안전 종료 및 VRAM 해제 스크립트 (stop_server.sh)
# ==============================================================================

set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "$SCRIPT_DIR/pyproject.toml" ]; then
    BASE_DIR="$SCRIPT_DIR"
elif [ -f "$SCRIPT_DIR/../pyproject.toml" ]; then
    BASE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
else
    BASE_DIR="$(pwd)"
fi
cd "$BASE_DIR"

PID_FILE="$BASE_DIR/vllm_serv.pid"
DASHBOARD_PID_FILE="$BASE_DIR/vllm_dashboard.pid"

COLOR_GREEN='\033[0;32m'
COLOR_YELLOW='\033[1;33m'
COLOR_RED='\033[0;31m'
COLOR_CYAN='\033[0;36m'
COLOR_NC='\033[0m'

stop_pid() {
    local target_pid=$1
    if [ -n "$target_pid" ] && ps -p "$target_pid" > /dev/null 2>&1; then
        echo -e "${COLOR_CYAN}[STOP] vllm_serv 프로세스(PID: $target_pid) 종료 시도 중 (SIGTERM)...${COLOR_NC}"
        kill "$target_pid" 2>/dev/null || true
        for i in {1..10}; do
            if ! ps -p "$target_pid" > /dev/null 2>&1; then
                echo -e "${COLOR_GREEN}✓ 프로세스 $target_pid 정상 종료 완료.${COLOR_NC}"
                return 0
            fi
            sleep 0.5
        done
        echo -e "${COLOR_YELLOW}[STOP] 강제 종료 수행 (SIGKILL)...${COLOR_NC}"
        kill -9 "$target_pid" 2>/dev/null || true
    fi
}

if [ -f "$PID_FILE" ]; then
    SAVED_PID=$(cat "$PID_FILE")
    stop_pid "$SAVED_PID"
    rm -f "$PID_FILE"
fi

if [ -f "$DASHBOARD_PID_FILE" ]; then
    SAVED_DASH_PID=$(cat "$DASHBOARD_PID_FILE")
    stop_pid "$SAVED_DASH_PID"
    rm -f "$DASHBOARD_PID_FILE"
fi

SERVER_PIDS=$(pgrep -f "src.api.server" || true)
if [ -n "$SERVER_PIDS" ]; then
    for pid in $SERVER_PIDS; do
        stop_pid "$pid"
    done
fi

DASH_PIDS=$(pgrep -f "uvicorn src.api.main:app" || true)
if [ -n "$DASH_PIDS" ]; then
    for pid in $DASH_PIDS; do
        stop_pid "$pid"
    done
fi

# llama-server 잔여 프로세스 추가 정리
LLAMA_PIDS=$(pgrep -f "llama-server" || true)
if [ -n "$LLAMA_PIDS" ]; then
    echo -e "${COLOR_CYAN}[STOP] 잔여 llama-server 하위 프로세스 정리 중: $LLAMA_PIDS${COLOR_NC}"
    for pid in $LLAMA_PIDS; do
        kill -9 "$pid" 2>/dev/null || true
    done
fi

rm -f "$PID_FILE" "$DASHBOARD_PID_FILE" 2>/dev/null || true

if command -v nvidia-smi &> /dev/null; then
    echo -e "${COLOR_GREEN}✓ VRAM 해제 상태 확인:${COLOR_NC}"
    nvidia-smi --query-gpu=memory.used,memory.total --format=csv,noheader
fi

echo -e "${COLOR_GREEN}✓ vllm_serv 서버 및 대시보드 프로세스 종료 완료.${COLOR_NC}"

EOF

chmod +x "$BASE_DIR/scripts/stop_server.sh"
ln -sf "$BASE_DIR/scripts/stop_server.sh" "$BASE_DIR/stop_server.sh"
log_info "✓ 생성 완료: scripts/stop_server.sh (루트 심볼릭 링크 ./stop_server.sh)"

# 4.3 status_server.sh 생성
cat << 'EOF' > "$BASE_DIR/scripts/status_server.sh"
#!/usr/bin/env bash
# ==============================================================================
# vllm_serv: 서빙 및 GPU VRAM 상태 확인 스크립트 (status_server.sh)
# ==============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "$SCRIPT_DIR/pyproject.toml" ]; then
    BASE_DIR="$SCRIPT_DIR"
elif [ -f "$SCRIPT_DIR/../pyproject.toml" ]; then
    BASE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
else
    BASE_DIR="$(pwd)"
fi
cd "$BASE_DIR"

PID_FILE="$BASE_DIR/vllm_serv.pid"
DASHBOARD_PID_FILE="$BASE_DIR/vllm_dashboard.pid"

COLOR_GREEN='\033[0;32m'
COLOR_YELLOW='\033[1;33m'
COLOR_RED='\033[0;31m'
COLOR_CYAN='\033[0;36m'
COLOR_NC='\033[0m'

echo -e "${COLOR_CYAN}====================================================${COLOR_NC}"
echo -e "${COLOR_CYAN} ⚡ vllm_serv 서버 및 멀티 플랫폼 하드웨어 리포트${COLOR_NC}"
echo -e "${COLOR_CYAN}====================================================${COLOR_NC}"

# 멀티 플랫폼 CPU / GPU 하드웨어 및 프로필 실시간 감지 리포트
uv run python -m src.core.cpu_detector --report 2>/dev/null || true

echo -e "\n[서버 프로세스 및 서비스 상태]"

PID=""
if [ -f "$PID_FILE" ]; then
    PID=$(cat "$PID_FILE")
fi

if [ -z "$PID" ] || ! ps -p "$PID" > /dev/null 2>&1; then
    PID=$(pgrep -f "src.api.server" | tail -n 1 || echo "")
fi

if [ -n "$PID" ] && ps -p "$PID" > /dev/null 2>&1; then
    echo -e "8081 메인 서버 프로세스: ${COLOR_GREEN}🟢 구동 중 (RUNNING, PID: $PID)${COLOR_NC}"
else
    echo -e "8081 메인 서버 프로세스: ${COLOR_YELLOW}⚪ 중지됨 (UNLOADED)${COLOR_NC}"
fi

DASH_PID=""
if [ -f "$DASHBOARD_PID_FILE" ]; then
    DASH_PID=$(cat "$DASHBOARD_PID_FILE")
fi
if [ -z "$DASH_PID" ] || ! ps -p "$DASH_PID" > /dev/null 2>&1; then
    DASH_PID=$(pgrep -f "uvicorn src.api.main:app" | tail -n 1 || echo "")
fi

if [ -n "$DASH_PID" ] && ps -p "$DASH_PID" > /dev/null 2>&1; then
    echo -e "8082 대시보드 프로세스  : ${COLOR_GREEN}🟢 구동 중 (RUNNING, PID: $DASH_PID)${COLOR_NC}"
else
    echo -e "8082 대시보드 프로세스  : ${COLOR_YELLOW}⚪ 중지됨 (UNLOADED)${COLOR_NC}"
fi

SERVER_HOST=$(uv run python -c "from src.core.config_manager import ConfigManager; print(ConfigManager().get_server_config().get('host', '127.0.0.1'))" 2>/dev/null || echo "127.0.0.1")
SERVER_PORT=$(uv run python -c "from src.core.config_manager import ConfigManager; print(ConfigManager().get_server_config().get('port', 8081))" 2>/dev/null || echo "8081")

LAN_IP=$(uv run python -c "from src.core.network_detector import NetworkDetector; print(NetworkDetector.get_active_lan_ips()[-1] if NetworkDetector.get_active_lan_ips() else '127.0.0.1')" 2>/dev/null || echo "127.0.0.1")

PROBE_HOSTS=("127.0.0.1" "localhost" "$LAN_IP")
if [ "$SERVER_HOST" != "0.0.0.0" ] && [ "$SERVER_HOST" != "127.0.0.1" ]; then
    PROBE_HOSTS+=("$SERVER_HOST")
fi

echo -e "\n[REST API 헬스체크 (http://${PROBE_HOSTS[0]}:$SERVER_PORT/health)]"
API_OK=0
if command -v curl &> /dev/null; then
    for host in "${PROBE_HOSTS[@]}"; do
        RESP=$(curl -sL --max-time 3 "http://$host:$SERVER_PORT/health" 2>/dev/null || echo "")
        if [ -n "$RESP" ] && echo "$RESP" | grep -q "status"; then
            echo "$RESP" | python3 -m json.tool 2>/dev/null || echo "$RESP"
            API_OK=1
            break
        fi
    done
fi
if [ "$API_OK" -eq 0 ]; then
    echo -e "${COLOR_YELLOW}응답 없음 (서버 미구현 또는 비활성)${COLOR_NC}"
fi

echo -e "\n[웹 대시보드 헬스체크 (http://${PROBE_HOSTS[0]}:8082/)]"
DASH_OK=0
if command -v curl &> /dev/null; then
    for host in "${PROBE_HOSTS[@]}"; do
        DASH_HTML=$(curl -sL --max-time 3 "http://$host:8082/" 2>/dev/null || echo "")
        if [ -z "$DASH_HTML" ]; then
            DASH_HTML=$(curl -sL --max-time 3 "http://$host:8082/dashboard/" 2>/dev/null || echo "")
        fi
        if echo "$DASH_HTML" | grep -qE "vLLM|Dashboard|vllm_serv|대시보드|LLM|Antigravity|Serving"; then
            echo -e "${COLOR_GREEN}🟢 대시보드 서비스 및 HTML DOM 정상 작동 중 (Port 8082 OPEN, DOM Verified)${COLOR_NC}"
            DASH_OK=1
            break
        elif [ -n "$DASH_HTML" ]; then
            echo -e "${COLOR_YELLOW}⚠️ 대시보드 포트 응답 수신되나 HTML DOM 키워드 검증 미달 (Port 8082 OPEN, Keyword Missing)${COLOR_NC}"
            DASH_OK=1
            break
        fi
    done
fi

if [ "$DASH_OK" -eq 0 ]; then
    SOCKET_BOUND=0
    if command -v lsof &>/dev/null && lsof -i:8082 &>/dev/null; then
        SOCKET_BOUND=1
    elif command -v ss &>/dev/null && ss -tulpn | grep -q ":8082"; then
        SOCKET_BOUND=1
    fi

    if [ "$SOCKET_BOUND" -eq 1 ]; then
        echo -e "${COLOR_GREEN}🟢 대시보드 포트 소켓 개방 확인 (Port 8082 OPEN)${COLOR_NC}"
    else
        echo -e "${COLOR_YELLOW}⚪ 대시보드 미구동 또는 포트 차단됨 (Port 8082 CLOSED)${COLOR_NC}"
    fi
fi


if command -v nvidia-smi &> /dev/null; then
    echo -e "\n[NVIDIA GPU VRAM 실시간 현황]"
    nvidia-smi --query-gpu=name,memory.used,memory.total,temperature.gpu --format=csv,noheader

    # T012: GPU 컴퓨트 프로세스 PID 리스트
    echo -e "\n[GPU 컴퓨트 프로세스 목록]"
    GPU_PROCS=$(nvidia-smi --query-compute-apps=pid,used_memory,name --format=csv,noheader 2>/dev/null)
    if [ -n "$GPU_PROCS" ]; then
        echo -e "PID, VRAM(MiB), Process"
        echo "$GPU_PROCS"
    else
        echo -e "${COLOR_YELLOW}GPU 컴퓨트 프로세스 없음${COLOR_NC}"
    fi
fi

# T012: llama-cpp-python CUDA 빌드 상태
echo -e "\n[CUDA 빌드 상태]"
if command -v nvcc &> /dev/null; then
    echo -e "nvcc: ${COLOR_GREEN}✓ $(nvcc --version 2>/dev/null | grep release | head -n 1)${COLOR_NC}"
else
    echo -e "nvcc: ${COLOR_RED}✗ 미감지${COLOR_NC}"
fi

CUDA_STATUS=$(uv run python -c "
import llama_cpp
fn = getattr(llama_cpp, 'llama_supports_gpu_offload', None) or getattr(llama_cpp, 'llama_supports_gpu', None)
print('True' if fn and fn() else 'False')
" 2>/dev/null || echo "Error")

if [ "$CUDA_STATUS" = "True" ]; then
    echo -e "llama-cpp-python GPU: ${COLOR_GREEN}✓ CUDA 가속 활성${COLOR_NC}"
else
    echo -e "llama-cpp-python GPU: ${COLOR_RED}✗ CPU 전용 모드${COLOR_NC}"
fi
EOF

chmod +x "$BASE_DIR/scripts/status_server.sh"
ln -sf "$BASE_DIR/scripts/status_server.sh" "$BASE_DIR/status_server.sh"
log_info "✓ 생성 완료: scripts/status_server.sh (루트 심볼릭 링크 ./status_server.sh)"

log_step "4.5 컨텍스트 윈도우 스케일링 벤치마크 (Smart Skip & Fallback)"

PROFILE_CACHE="$BASE_DIR/config/model_context_profiles.json"
if [ "$SKIP_BENCHMARK" -eq 1 ]; then
    log_info "⏩ --skip-benchmark 옵션 감지: Step 4.5 컨텍스트 윈도우 스케일링 벤치마크를 스킵합니다."
    "$VENV_PYTHON" "$BASE_DIR/scripts/benchmark_context_window.py" --skip-benchmark || log_warn "benchmark_context_window.py --skip-benchmark 실행 중 경고 발생"
elif [ -f "$PROFILE_CACHE" ]; then
    log_info "⚡ Step 2.8에서 실측 벤치마크 및 캐시 생성 완납 감지 ($PROFILE_CACHE)."
    log_info "Step 4.5 캐시 프로필 재활용으로 고속 스킵 (Smart Skip)..."
    "$VENV_PYTHON" "$BASE_DIR/scripts/benchmark_context_window.py" --skip-benchmark || log_warn "Smart Skip 프로필 검증 중 경고 발생"
elif [ "$FORCE_BENCHMARK" -eq 1 ]; then
    log_info "🔥 --force-benchmark 옵션 감지: 카탈로그 전체 LLM 후보 모델 대상 실측 스케일링 벤치마크를 수행합니다..."
    "$VENV_PYTHON" "$BASE_DIR/scripts/benchmark_context_window.py" --force-benchmark || \
    log_warn "컨텍스트 벤치마크 실측 실패/건너뜀 (기본 프로필로 진행)."
else
    log_info "컨텍스트 윈도우 실측 벤치마크 실행 및 config/model_context_profiles.json 캐싱 중..."
    "$VENV_PYTHON" "$BASE_DIR/scripts/benchmark_context_window.py" || \
    log_warn "컨텍스트 벤치마크 실측 실패/건너뜀 (기본 프로필로 진행)."
fi

log_step "4.6 SQLite Metrics DB & Seed Pack 초기화 (045-db-seed-and-setup-integration)"
mkdir -p "$BASE_DIR/data"
if [ ! -f "$BASE_DIR/data/metrics.db" ]; then
    log_info "data/metrics.db 부재 감지. 초기 시드 데이터 팩 자동 주입 중..."
    uv run python "$BASE_DIR/scripts/seed_db.py" || log_warn "시드 DB 주입 실패 (기본 구조로 대체)."
else
    log_info "✓ 기존 data/metrics.db 유지 완료."
fi

log_step "5. setup.sh 설정 완결"
chmod +x "$BASE_DIR/scripts"/*.sh "$BASE_DIR"/*.sh 2>/dev/null || true
log_info "✓ 전역 제어 스크립트 실행 권한 (chmod +x) 갱신 완료."

# ==============================================================================
# Step Final: SUDO_USER Ownership Remediation
# (039-seed-pack-sudo-firewall-migration: FR-007, DoD-004)
# ==============================================================================
if [ -n "$SUDO_USER" ] && [ "$SUDO_USER" != "root" ]; then
    log_info "root 실행 감지 (SUDO_USER=$SUDO_USER). 파일 소유권 자동 환원을 수행합니다."
    CHOWN_TARGETS=()
    [ -d "$BASE_DIR/.venv" ] && CHOWN_TARGETS+=("$BASE_DIR/.venv")
    [ -d "$BASE_DIR/logs" ] && CHOWN_TARGETS+=("$BASE_DIR/logs")
    [ -d "$BASE_DIR/config" ] && CHOWN_TARGETS+=("$BASE_DIR/config")

    if [ ${#CHOWN_TARGETS[@]} -gt 0 ]; then
        chown -R "$SUDO_USER:$SUDO_USER" "${CHOWN_TARGETS[@]}"
        log_info "✓ root 실행 감지: $SUDO_USER 계정으로 소유권 자동 환원 완료."
        for target in "${CHOWN_TARGETS[@]}"; do
            log_info "  - $(basename "$target")/ → $SUDO_USER:$SUDO_USER"
        done
    else
        log_info "소유권 환원 대상 디렉토리가 존재하지 않습니다. 건너뜁니다."
    fi
elif [ "$EUID" -eq 0 ] && [ -z "$SUDO_USER" ]; then
    log_warn "순수 root 계정으로 직접 실행 중입니다. .venv, logs, config 소유권이 root:root로 유지됩니다."
    log_warn "일반 사용자 계정으로 서버를 구동하려면 'sudo -u <계정> ./setup.sh' 또는 일반 계정에서 실행을 권장합니다."
fi

log_info "🚀 [FR-007] 최적 서빙 모델 및 프로필 기반 서버 자동 구동 및 서빙 복구 중..."
if [ -f "$BASE_DIR/start_server.sh" ]; then
    "$BASE_DIR/start_server.sh" || log_warn "서버 자동 구동 중 경고 발생 (수동 ./start_server.sh 구동 가능)"
elif [ -f "$BASE_DIR/scripts/start_server.sh" ]; then
    "$BASE_DIR/scripts/start_server.sh" || log_warn "서버 자동 구동 중 경고 발생 (수동 ./start_server.sh 구동 가능)"
fi

log_info "vllm_serv 환경 설정 및 제어 스크립트 생성이 완료되었습니다!"
echo -e "\n사용 가능한 제어 명령어:"
echo -e "  - 서버 구동: ${COLOR_GREEN}./start_server.sh${COLOR_NC} (또는 ./scripts/start_server.sh)"
echo -e "  - 서버 종료: ${COLOR_GREEN}./stop_server.sh${COLOR_NC} (또는 ./scripts/stop_server.sh)"
echo -e "  - 상태 확인: ${COLOR_GREEN}./status_server.sh${COLOR_NC} (또는 ./scripts/status_server.sh)\n"

